[theme]
# Streamlit theme configuration
primaryColor = "#2ecc71"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
# Server configuration
maxUploadSize = 10
enableXsrfProtection = true
enableCORS = false
